name: Affirmation Form
description: Submit an affirmation for your developer besties
title: "[affirm]: <title>"
labels: ["affirmation"]
body:
  - type: textarea
    id: affirmation
    attributes:
      label: Affirmation
      placeholder: I will affirm me and my fellow brethren today
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      placeholder: author@email.com
    validations:
      required: true
