name: Submit Affirmation via Issues
on:
  issue_comment:
    types: [created, edited]

jobs:
  approval:
    # this job only runs for issue comments
    name: Check if Affirmation is approved
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.number }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check if authorized member has approved affirmation
        run: |
          pip install requests
          python ${GITHUB_WORKSPACE}/.github/helper/approval.py
        env:
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  contribution:
    name: Extract, Commit & Push Affirmation to default branch
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: ${GITHUB_WORKSPACE}/.github/ISSUE_TEMPLATE/submit_affirmation.yml

      - name: Update affirmations file
        run: python ${GITHUB_WORKSPACE}/.github/helper/update.py
        env:
          affirmation: ${{ steps.issue-parser.outputs.jsonString }}

      - name: Commit + Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: '${{ fromJson(steps.issue-parser.outputs.jsonString).author }}'
          author_email: '${{ fromJson(steps.issue-parser.outputs.jsonString).author }}'
          message: 'feat: Affirmation submission via Issue'

  cleanup:
    name: Close Issue thread after successful contribution
    runs-on: ubuntu-latest
    needs: contribution
    steps:
      - run: echo "We're all done now...Feel free to close this issue thread now :D"
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue since commit has been pushed to main branch
